<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="models\in2509三帆商贸账单明细.cs" />
    <Compile Remove="models\in2509中研创科账单明细.cs" />
    <Compile Remove="models\in2509丰诺融道账单明细.cs" />
    <Compile Remove="models\in2509仁生泽发账单明细.cs" />
    <Compile Remove="models\in2509众帮账单明细.cs" />
    <Compile Remove="models\in2509众臣电子账单明细.cs" />
    <Compile Remove="models\in2509众鲜味来账单明细.cs" />
    <Compile Remove="models\in2509农产品账单明细.cs" />
    <Compile Remove="models\in2509刘广账单明细.cs" />
    <Compile Remove="models\in2509创美地毯厂账单明细入仓.cs" />
    <Compile Remove="models\in2509千希语望账单明细.cs" />
    <Compile Remove="models\in2509华天海鲜账单明细.cs" />
    <Compile Remove="models\in2509呜啊商贸账单明细.cs" />
    <Compile Remove="models\in2509嘉多灵账单明细.cs" />
    <Compile Remove="models\in2509国冠账单明细.cs" />
    <Compile Remove="models\in2509宏成亚信账单明细.cs" />
    <Compile Remove="models\in2509尚都账单明细.cs" />
    <Compile Remove="models\in2509尺子账单明细.cs" />
    <Compile Remove="models\in2509广昌县飞梦账单明细.cs" />
    <Compile Remove="models\in2509廷思文化账单明细.cs" />
    <Compile Remove="models\in2509思百盈账单明细.cs" />
    <Compile Remove="models\in2509文森显账单明细.cs" />
    <Compile Remove="models\in2509文行研学账单明细.cs" />
    <Compile Remove="models\in2509晟驰仓储账单明细入仓.cs" />
    <Compile Remove="models\in2509智德文化账单明细.cs" />
    <Compile Remove="models\in2509朱文龙账单明细.cs" />
    <Compile Remove="models\in2509李海英账单明细.cs" />
    <Compile Remove="models\in2509树米账单明细.cs" />
    <Compile Remove="models\in2509槊恒账单明细.cs" />
    <Compile Remove="models\in2509沃正账单明细.cs" />
    <Compile Remove="models\in2509河北养道肥料账单明细.cs" />
    <Compile Remove="models\in2509王晓丰账单明细.cs" />
    <Compile Remove="models\in2509王超账单明细.cs" />
    <Compile Remove="models\in2509瑞涵账单明细入仓.cs" />
    <Compile Remove="models\in2509瑞涵账单明细揽收.cs" />
    <Compile Remove="models\in2509申清艳账单明细.cs" />
    <Compile Remove="models\in2509白超账单明细.cs" />
    <Compile Remove="models\in2509石川钓具账单明细.cs" />
    <Compile Remove="models\in2509石药惠盛账单明细.cs" />
    <Compile Remove="models\in2509祝年堂账单明细.cs" />
    <Compile Remove="models\in2509米莱账单明细.cs" />
    <Compile Remove="models\in2509维喜账单明细.cs" />
    <Compile Remove="models\in2509绿航商贸账单明细.cs" />
    <Compile Remove="models\in2509美妍澄账单明细.cs" />
    <Compile Remove="models\in2509芬芳账单明细.cs" />
    <Compile Remove="models\in2509萱草账单明细.cs" />
    <Compile Remove="models\in2509蒙友账单明细.cs" />
    <Compile Remove="models\in2509蓓斯蓝琦账单明细.cs" />
    <Compile Remove="models\in2509贝爱账单明细.cs" />
    <Compile Remove="models\in2509赵玉龙账单明细.cs" />
    <Compile Remove="models\in2509趣爪坊账单明细.cs" />
    <Compile Remove="models\in2509金尘茶账单明细.cs" />
    <Compile Remove="models\in2509金石通达账单明细.cs" />
    <Compile Remove="models\in2509鑫洁源账单明细.cs" />
    <Compile Remove="models\in2509长安婴爵玩具账单明细.cs" />
    <Compile Remove="models\in2509阿拉善账单明细.cs" />
    <Compile Remove="models\in2509雅列奇账单明细.cs" />
    <Compile Remove="models\in2509雷奥账单明细.cs" />
    <Compile Remove="models\in2509鲜享账单明细.cs" />
    <Compile Remove="models\in2509鲜享账单明细正定.cs" />
    <Compile Remove="models\in2509鼎汉账单明细总.cs" />
    <Compile Remove="models\out2509世诺账单明细.cs" />
    <Compile Remove="models\out2509丰诺账单明细.cs" />
    <Compile Remove="models\out2509乾皓账单明细.cs" />
    <Compile Remove="models\out2509于海涛账单明细.cs" />
    <Compile Remove="models\out2509于雷账单明细.cs" />
    <Compile Remove="models\out2509付小飞账单明细.cs" />
    <Compile Remove="models\out2509何佳林账单明细.cs" />
    <Compile Remove="models\out2509保定仓内部定价账单明细.cs" />
    <Compile Remove="models\out2509冀鹏海丰账单明细.cs" />
    <Compile Remove="models\out2509冯伟伟账单明细.cs" />
    <Compile Remove="models\out2509冯国虎账单明细1.cs" />
    <Compile Remove="models\out2509刘建华账单明细.cs" />
    <Compile Remove="models\out2509创美地毯厂账单明细揽收.cs" />
    <Compile Remove="models\out2509吴少希账单明细.cs" />
    <Compile Remove="models\out2509国药乐仁堂账单明细.cs" />
    <Compile Remove="models\out2509宋翠翠账单明细.cs" />
    <Compile Remove="models\out2509张世聪账单明细.cs" />
    <Compile Remove="models\out2509张吉鹏账单明细.cs" />
    <Compile Remove="models\out2509张哲账单明细.cs" />
    <Compile Remove="models\out2509张玉芳账单明细.cs" />
    <Compile Remove="models\out2509怪兽胖柒账单明细.cs" />
    <Compile Remove="models\out2509扬杰账单明细.cs" />
    <Compile Remove="models\out2509掘澜账单明细.cs" />
    <Compile Remove="models\out2509昂强商贸账单明细.cs" />
    <Compile Remove="models\out2509晟年账单明细.cs" />
    <Compile Remove="models\out2509晟驰伍肆伍账单明细揽收.cs" />
    <Compile Remove="models\out2509普若米斯账单明细.cs" />
    <Compile Remove="models\out2509曜诚账单明细.cs" />
    <Compile Remove="models\out2509曹少培账单明细.cs" />
    <Compile Remove="models\out2509曹赛账单明细.cs" />
    <Compile Remove="models\out2509李云华统账单明细.cs" />
    <Compile Remove="models\out2509李冬冬账单明细.cs" />
    <Compile Remove="models\out2509李哲账单明细.cs" />
    <Compile Remove="models\out2509李宏超账单明细.cs" />
    <Compile Remove="models\out2509李爱民账单明细.cs" />
    <Compile Remove="models\out2509李磊账单明细.cs" />
    <Compile Remove="models\out2509李贺维账单明细.cs" />
    <Compile Remove="models\out2509李辉发账单明细.cs" />
    <Compile Remove="models\out2509杨军利账单明细.cs" />
    <Compile Remove="models\out2509杨子伟梅花网点账单明细.cs" />
    <Compile Remove="models\out2509杨子伟账单明细.cs" />
    <Compile Remove="models\out2509王培静2账单明细.cs" />
    <Compile Remove="models\out2509王培静账单明细.cs" />
    <Compile Remove="models\out2509王展账单明细.cs" />
    <Compile Remove="models\out2509王飞账单明细.cs" />
    <Compile Remove="models\out2509瑞涵账单明细揽收.cs" />
    <Compile Remove="models\out2509画心账单明细.cs" />
    <Compile Remove="models\out2509眭若尘账单明细.cs" />
    <Compile Remove="models\out2509石家庄晨华文具有限公司账单明细.cs" />
    <Compile Remove="models\out2509纳才云仓账单明细.cs" />
    <Compile Remove="models\out2509纸管家账单明细.cs" />
    <Compile Remove="models\out2509美环网络科技账单明细.cs" />
    <Compile Remove="models\out2509苗伟账单明细.cs" />
    <Compile Remove="models\out2509赵春霞账单明细.cs" />
    <Compile Remove="models\out2509郎俊忠账单明细.cs" />
    <Compile Remove="models\out2509郑煜账单明细.cs" />
    <Compile Remove="models\out2509郝梓铭账单明细.cs" />
    <Compile Remove="models\out2509郭永波账单明细.cs" />
    <Compile Remove="models\out2509陈占芳账单明细.cs" />
    <Compile Remove="models\out2509雷鸣账单明细.cs" />
    <Compile Remove="models\out2509霍文宝账单明细.cs" />
    <Compile Remove="models\out2509霍锐开账单明细.cs" />
    <Compile Remove="models\out2509顶顶香账单明细.cs" />
    <Compile Remove="models\out2509鱼欢账单明细.cs" />
    <Compile Remove="models\out2509黄兴芹账单明细.cs" />
    <Compile Remove="models\out2509黄赛账单明细.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MiniExcel" Version="1.41.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZR.Common\ZR.Common.csproj" />
  </ItemGroup>

</Project>