<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MiniExcel" Version="1.42.0" />
    <PackageReference Include="PDFsharp" Version="6.2.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZR.Common\ZR.Common.csproj" />
  </ItemGroup>

</Project>